spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: ticket-service
          uri: https://ticket.up.railway.app/api/ticket
          predicates:
            - Host=**.railway.app
        - id: ticket-service
          uri: https://ticket.up.railway.app/api/payment
          predicates:
            - Host=**.railway.app
        - id: UserService
          uri: https://ticket.up.railway.app/api/user/**
          predicates:
            - Host=**.railway.app
  application:
    name: gateway

server:
  port: 8082