spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      routes:
        - id: ticket-service
          uri: https://ticket.up.railway.app
          predicates:
            - Host=**.railway.app
            - Path=/api/ticket/**
        - id: ticket-service
          uri: https://ticket.up.railway.app
          predicates:
            - Host=**.railway.appgit 
            - Path=/api/payment/**
        - id: user-service
          uri: https://user.up.railway.app
          predicates:
            - Host=**.railway.app
            - Path=/api/user/**
  application:
    name: gateway

server:
  port: 8082
